### ISSUE TITLE
will code be posted? what is status on the publication?

### ISSUE THREAD

**Issue by cottrell** [frgsimpson/kitt#1]

**Comment by frgsimpson** [comment]
Thanks for the reminder! Yes I'll aim to post the code later this week. 

The published version of the paper can be found here:
https://proceedings.neurips.cc/paper/2021/hash/56c3b2c6ea3a83aaeeff35eeb45d700d-Abstract.html

**Comment by 1firestone** [comment]
When would code be posted?Thank you

**Comment by frgsimpson** [comment]
Sorry for the delay, it's now up. Please let me know if you have any questions! I can also provide a link to a pretrained model.

**Comment by cottrell** [comment]
do you have more recent/complete instructions to install the env? Nothing I've tried is working so far.  The README.md also references a non-existant setup.py ... I can open another issue if that is helpful. I've tried with python 3.7 as the toml file indicates. keras was missing for example.

If you have a working environment maybe just doing a pip freeze and dumping the requirements would be enough. There are a lot of wild cards in the toml file.

**Comment by frgsimpson** [comment]
Ah sorry about this, will try to fix it tomorrow! I think I updated the code to use external keras but didnt update poetry.

**Comment by frgsimpson** [comment]
@cottrell I've just pushed an update - fixed the keras imports, and updated the readme. I was then able to make a clean install that passed tests using:
poetry env use python3.7
poetry install
I've also added a requirements.txt that was exported from the poetry env.

Hope that helps, let me know if you have any issues!

**Comment by cottrell** [comment]
I seem to be closer to running now ... just hitting various errors to do with missing files when I follow the README.md.

```
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/home/cottrell/dev/kitt/datasets/64_4d_max_exp_1_prod_2_random_inputs/train.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Exception ignored in: <function Dataset.__del__ at 0x7faf5080c710>
Traceback (most recent call last):
  File "/home/cottrell/dev/kitt/kitt/utils/training.py", line 48, in __del__
    self._train.close()
AttributeError: 'Dataset' object has no attribute '_train'
```

I guess before burning more of your time, I should try to understand if there are no trained models (weights) in the repo or stored somewhere else.

**Comment by frgsimpson** [comment]
@cottrell Ah I think you might first need to run the script for generating the training data (which are draws from Gaussian Processes), but I've also posted a trained model here:

https://drive.google.com/drive/folders/1AeyEbAYMGYIkRNFTGL-b2s-HQvtHUQDd?usp=sharing

**Comment by cottrell** [comment]
In case it helps anyone else, got this running. Have pushed some notes on a fork. FYI, it even seems to run (inference not train) on current (as of my writing this) latest tensorflow and python3.11

**Comment by cottrell** [comment]
If anyone manages to get this to work (inference on a custom dataset) would be interesting to post here. I think for future, it would be best to use a zero wildcard pure Dockerfile (docker image even better) to maximize probability of repdoducibility. Also git-lfs can be used for final binary blobs.
